app:
  name: example-go-api
  env: development
  port: 8089
  debug: true

database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  user: root
  password: "@123456@"
  name: example_db
  charset: utf8mb4
  parse_time: true
  loc: Local

jwt:
  secret: 432d7dc86437d09e9ba68e8d2572525c
  issuer: HS256
  access_token_ttl: 60000
  refresh_token_ttl: 43200000

log:
  level: debug  
  file: logs/app.log

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  repo_cache_ttl: 5

storage:
  provider: local
  prefix_route: /public

  local:
    base_path: ./storages/uploads
    max_size_mb: 100

  s3:
    bucket:
    region:
    access_key:
    secret_key:
    endpoint:
    max_size_mb: 100

  cache:
    path: ./storages/cache
    max_age_min: 2
    cleanup_interval_min: 1